### PR TITLE
Added colorizeSync function

### PR DESCRIPTION
**Pull request by tforgione**
Added a function to use colorize function in a synchronous way

When I tried to test it, I had an error, even without touching anything, so I don't know what to think about it.
Feel free to try it and merge if you like it.

### CODE REVIEW

**Comment by pksunkara** [comment]
Can you paste the logs of the error you are getting? Thanks.

**Comment by tforgione** [comment]
```
$ npm test

> pygments@0.2.0 test /home/thomas/pygments.js
> vows pygments-test.js --spec

 
  ♢ Pygments Test 
  
✗ Errored » 1 errored

npm ERR! Test failed.  See above for more details.
```

Am I missing something ? Is `npm test` the right command to test ? Is it normal that I don't have more information than that ?

**Comment by pksunkara** [comment]
I think it's an issue with the nodejs version test suite.

**Comment by tforgione** [comment]
Yes, it's really weird. I'm not familiar with vows, but if I use this as `pygments-test.js` : 

``` js
/*
 * pygments.js: A node.js wrapper for pygments
 *
 * (C) 2011, Pavan Kumar Sunkara
 *
 */

var vows = require('vows'),
    assert = require('assert'),
    fs = require('fs');

var pygments = require('./pygments');

vows.describe('Pygments Test').addBatch({
  'Pygments': {
    'trivial': function (pygments) {
       assert.isTrue (true);
    }
  }
}).export(module);
```

it still fails with 

```
$ npm test

> pygments@0.2.0 test /home/thomas/pygments.js
> vows pygments-test.js --spec

 
  ♢ Pygments Test 
  
✗ Errored » 1 errored

npm ERR! Test failed.  See above for more details.
```

I don't really know what to think about it

**Comment by pksunkara** [comment]
What's your nodejs and vows version?

**Comment by tforgione** [comment]
```
$ node --version
v6.3.1
``` 
```
$ vows --version
(node:15487) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
vows 0.8.1
```

**Comment by pksunkara** [comment]
Can you try with node 0.12?

**Comment by tforgione** [comment]
Ok, so I figured out the problem. My global version of `vows` (which is the one that is called when I run `npm test`) was not the same as the one in your `package.json`, so everything is fine now.

**Comment by pksunkara** [comment]
Will you be writing the test?

**Comment by tforgione** [comment]
Mmh, I added two functions which are `colorizeSync` and `executeSync`, and they correspond to the functions `colorize` and `execute` (which are not in your tests, am I right ?).

I also added a function `prepareColorizeParameters` in order to avoid duplication between `colorize` and `colorizeSync`.

What do you want me to test exactly ?

**Comment by pksunkara** [comment]
Nvm.

**Comment by tforgione** [comment]
Thanks, I hope I didn't bother you too much.

The thing is that I really wanted to use that piece of code in a synchronous way, and I didn't want to steal your code, and that's why I made this pull request.

Will you `npm publish` soon ?

**Comment by pksunkara** [comment]
Published

**Comment by tforgione** [comment]
Thank you very much, I apologize for the inconvenience.

**Pull request merged**
